---
project_paths:
- app/controllers
- app/helpers
source_repo: https://github.com/solidusio/solidus_frontend.git
source_name: solidus_frontend
source_branch: master
source_base_path: "./"
local_base_path: templates/
ignore:
- path: app/controllers
  diffs:
  - file: app/controllers/spree/checkout_controller.rb
    skip: true
  - file: templates/app/controllers/spree/user_confirmations_controller.rb
    skip: true
  - file: templates/app/controllers/spree/user_passwords_controller.rb
    skip: true
  - file: templates/app/controllers/spree/user_registrations_controller.rb
    skip: true
  - file: templates/app/controllers/spree/users_controller.rb
    skip: true
  - file: templates/app/controllers/spree/user_sessions_controller.rb
    skip: true
  - file: templates/app/controllers/concerns/solidus_starter_frontend/taxonomies.rb
    skip: true
  - hash: 3258206090
    file: app/controllers/spree/coupon_codes_controller.rb
  - hash: 270376296
    file: app/controllers/spree/home_controller.rb
  - hash: 3266230916
    file: app/controllers/spree/products_controller.rb
  - hash: 2687797976
    file: app/controllers/spree/store_controller.rb
  - hash: 3411057011
    file: app/controllers/spree/taxons_controller.rb
  - hash: 1926803060
    file: app/controllers/spree/content_controller.rb
- path: app/helpers
  diffs:
  - hash: 1254388106
    file: templates/app/helpers/spree/product_options_helper.rb
